# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4L-2dKmdUYLG1nQP6A7JOknn3yTQUJC
"""

import numpy as np
chi2_lcdm = 7886.2
chi2_klocr = 7441.23
delta_chi2 = chi2_lcdm - chi2_klocr
sigma = np.sqrt(delta_chi2)
print("KLOCR VERIFICATION TEST")
print("chi2_LCDM =", chi2_lcdm)
print("chi2_KLOCR =", chi2_klocr)
print("Delta Chi2 =", delta_chi2)
print("Sigma =", sigma)
print("SIGNIFICANCE =", round(sigma, 2), "sigma")
print("K0 = 0.917, H0 = 73.0, w = -1.03")
print("RESULT: BOM CONFIRMED IF SIGMA > 20")